import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "../components/common/Header";
import styles from '../styles/gridPageLayout.module.css'
import homeStyles from '../styles/homePage.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Rate The Docs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles['wrapper'] + ' ' + homeStyles['home'] + ' ' + 'text-white min-h-screen flex flex-col items-center'}>
        <Header />
        <main className="flex  items-center max-w-7xl">
          <section className={" flex-1 items-center text-purple-200 bg-[#ffffff10] shadow-2xl backdrop-blur-sm rounded-3xl text-lg flex justify-center gap-20 p-10"}>
            <h1 className={homeStyles['heading'] + ' text-[floralwhite] '}>
              <span className={homeStyles['curly'] + ' ' + "text-[darkturquoise] text-6xl"}>community-driven</span>{' '}
              <span className="text-[yellowgreen]">feedback</span>
              <span className="text-rose-500 font-normal">|</span>
              <span className="text-[mediumpurple]">rating</span>{' '}
              <p className="text-4xl font-normal">system for package documentation</p>
            </h1>
            <Link href={'./ratings'} className='transition-colors bg-purple-600 hover:bg-purple-500 py-3 px-8 h-fit rounded-lg text-2xl shadow-xl text-white'>Participate</Link>
          </section>
        </main>
      </div>
    </>
  );
};

export default Home;
