import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Header from "../components/common/Header";
import { trpc } from "../utils/trpc";
import styles from '../styles/gridPageLayout.module.css'
import PendingProposals from "../components/proposals/pending";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles['wrapper']}>
        <Header />
        <PendingProposals />
      </main>
    </>
  );
};

export default Home;
