import React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/common/Header";
import Ratings from "../features/ratings";
import styles from '../styles/gridPageLayout.module.css'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.wrapper}>
        <Header />
        <Ratings />
      </main>
    </>
  );
};

export default Home;
